Wpmlpb 149
OnTheGoSystems/wpml-page-builders-beaver-builder pull request #6
Opened 2018-08-09 18:16 UTC by adrianosferreira

2018-08-09 18:20 UTC, adrianosferreira commented
@BruceOnTheGo Beaver Builder also covered, please check.

2018-08-09 20:05 UTC, strategio submitted a review, later dismissed

2018-08-10 09:10 UTC, brucepearson submitted a review, later dismissed
@adrianosferreira Looks good. +1

2018-08-22 08:21 UTC, andreasciamanna requested changes
@adrianosferreira please either fix this branch or close it. Packagist is spamming me because of the error in the composer.json file.

2018-08-22 08:21 UTC, andreasciamanna commented on composer.json
> +    "wpml/page-builders": "dev-wpmlpb-149",
@adrianosferreira please, whenever you make a change in the composer.json file, test it by running `composer install`: this one has trailing comma which will cause errors.

2018-08-22 11:18 UTC, adrianosferreira commented on composer.json
> +    "wpml/page-builders": "dev-wpmlpb-149",
@andreasciamanna done.

2018-08-22 11:25 UTC, andreasciamanna approved these changes

2018-08-22 11:26 UTC, andreasciamanna commented
@BruceOnTheGo I think you forgot to approve this PR

2018-08-24 11:54 UTC, merged